import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import { Header } from "@/components/layout/header";
import "./globals.css";

const fontSans = Fira_Code({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${fontSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
